/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author killer
 */
public class Tic2 extends javax.swing.JFrame {

    /**
     * Creates new form Tic2
     */
    int coins1;
    int coins2;
    boolean th=false;
    int[][] arr=new int[3][3];
    String a;
    String b;
    
    public Tic2(String a,String b) {
        initComponents();
        coins2=5;
        coins1=5;
        this.a=a;
        this.b=b;
        for(int i=0;i<=2;i++){
            for(int j=0;j<=2;j++){
                arr[i][j]=0;
            }
        }
      
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        _00 = new javax.swing.JLabel();
        _01 = new javax.swing.JLabel();
        _02 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        _20 = new javax.swing.JLabel();
        _21 = new javax.swing.JLabel();
        _22 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        _10 = new javax.swing.JLabel();
        _11 = new javax.swing.JLabel();
        _12 = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jLabel6.setText("jLabel1");

        jLabel8.setText("jLabel1");

        jLabel1.setText("jLabel1");

        jPanel4.setBackground(new java.awt.Color(234, 234, 39));

        jLabel11.setText("jLabel2");

        jLabel12.setText("jLabel3");

        jLabel13.setText("jLabel5");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel7.setText("jLabel7");

        jToggleButton1.setText("jToggleButton1");

        jPanel6.setBackground(new java.awt.Color(234, 234, 39));

        jLabel17.setBackground(new java.awt.Color(241, 240, 242));
        jLabel17.setText("jLabel2");

        jLabel18.setText("jLabel3");

        jLabel19.setText("jLabel5");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(44, 44, 44))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 191, 41));

        jPanel2.setBackground(new java.awt.Color(234, 234, 39));

        _00.setBackground(new java.awt.Color(241, 240, 242));
        _00.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png")); // NOI18N
        _00.setText(" ");
        _00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _00MouseClicked(evt);
            }
        });

        _01.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png")); // NOI18N
        _01.setText("*********");
        _01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _01MouseClicked(evt);
            }
        });

        _02.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png")); // NOI18N
        _02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _02MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_00, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(_01, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(_02)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(_00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(234, 234, 39));

        _20.setBackground(new java.awt.Color(241, 240, 242));
        _20.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png")); // NOI18N
        _20.setText("**********");
        _20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _20MouseClicked(evt);
            }
        });

        _21.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png")); // NOI18N
        _21.setText("**********");
        _21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _21MouseClicked(evt);
            }
        });

        _22.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png")); // NOI18N
        _22.setText(" ");
        _22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_21, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(_22)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_20)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(_22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(234, 234, 39));

        _10.setBackground(new java.awt.Color(241, 240, 242));
        _10.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png")); // NOI18N
        _10.setText("**********");
        _10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _10MouseClicked(evt);
            }
        });

        _11.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png")); // NOI18N
        _11.setText("**********");
        _11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _11MouseClicked(evt);
            }
        });

        _12.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png")); // NOI18N
        _12.setText(" ");
        _12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(_12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        msg.setText("  ");

        jLabel2.setFont(new java.awt.Font("URW Chancery L", 3, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(67, 0, 255));
        jLabel2.setText("           Wellcome");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.red, null, null));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("quit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("URW Chancery L", 0, 18)); // NOI18N
        jLabel3.setText("Uppyupender");

        jButton3.setText("Back <--");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(msg)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(93, 93, 93))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__00MouseClicked
        if(arr[0][0]==0){
        if((coins1==0)&&(th==false))
          msg.setText("coins over//");
      if((coins2==0)&&(th==true))
          msg.setText("coins over//");
      else{
          
           if(th){
               coins2--;
               
           _00.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/2.png")); 
           arr[0][0]=2;
           chk(2);
         }
        else
        {   coins1--;
           _00.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/1.png")); 
           arr[0][0]=1; 
           chk(1);
        }
         
      }
       if(th)
           th=false;
       else
           th=true;
        }
    }//GEN-LAST:event__00MouseClicked

    private void _01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__01MouseClicked
        if(arr[0][1]==0){
        if((coins1==0)&&(th==false))
          msg.setText("coins over//");
      if((coins2==0)&&(th==true))
          msg.setText("coins over//");
      else{
          
           if(th){
               coins2--;
           _01.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/2.png")); 
           arr[0][1]=2;
           chk(2);
         }
        else
        {   coins1--;
           _01.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/1.png")); 
           arr[0][1]=1; 
           chk(1);
        }
         
      }
       if(th)
           th=false;
       else
           th=true;
        }
    }//GEN-LAST:event__01MouseClicked

    private void _02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__02MouseClicked
         if(arr[0][2]==0){
        if((coins1==0)&&(th==false))
          msg.setText("coins over//");
      if((coins2==0)&&(th==true))
          msg.setText("coins over//");
      else{
          
           if(th){
               coins2--;
           _02.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/2.png")); 
           arr[0][2]=2;
           chk(2);
         }
        else
        {   coins1--;
           _02.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/1.png")); 
           arr[0][2]=1; 
           chk(1);
        }
         
      }
       if(th)
           th=false;
       else
           th=true;
         }
    }//GEN-LAST:event__02MouseClicked

    private void _10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__10MouseClicked
       if(arr[1][0]==0){
        if((coins1==0)&&(th==false))
          msg.setText("coins over//");
      if((coins2==0)&&(th==true))
          msg.setText("coins over//");
      else{
          
           if(th){
               coins2--;
           _10.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/2.png")); 
           arr[1][0]=2;
           chk(2);
         }
        else
        {   coins1--;
           _10.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/1.png")); 
           arr[1][0]=1; 
           chk(1);
        }
         
      }
       if(th)
           th=false;
       else
           th=true;
       }
    }//GEN-LAST:event__10MouseClicked

    private void _11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__11MouseClicked
         if(arr[1][1]==0){
        if((coins1==0)&&(th==false))
          msg.setText("coins over//");
      if((coins2==0)&&(th==true))
          msg.setText("coins over//");
      else{
          
           if(th){
               coins2--;
           _11.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/2.png")); 
           arr[1][1]=2;
           chk(2);
         }
        else
        {   coins1--;
           _11.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/1.png")); 
           arr[1][1]=1; 
           chk(1);
        }
         
      }
       if(th)
           th=false;
       else
           th=true;
         }
    }//GEN-LAST:event__11MouseClicked

    private void _12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__12MouseClicked
         if(arr[1][2]==0){
        if((coins1==0)&&(th==false))
          msg.setText("coins over//");
      if((coins2==0)&&(th==true))
          msg.setText("coins over//");
      else{
          
           if(th){
               coins2--;
           _12.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/2.png")); 
           arr[1][2]=2;
           chk(2);
         }
        else
        {   coins1--;
           _12.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/1.png")); 
           arr[1][2]=1; 
           chk(1);
        }
         
      }
       if(th)
           th=false;
       else
           th=true;
         }
    }//GEN-LAST:event__12MouseClicked

    private void _20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__20MouseClicked
         if(arr[2][0]==0){
        if((coins1==0)&&(th==false))
          msg.setText("coins over//");
      if((coins2==0)&&(th==true))
          msg.setText("coins over//");
      else{
          
           if(th){
               coins2--;
           _20.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/2.png")); 
           arr[2][0]=2;
           chk(2);
         }
        else
        {   coins1--;
           _20.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/1.png")); 
           arr[2][0]=1; 
           chk(1);
        }
         
      }
       if(th)
           th=false;
       else
           th=true;
         }
    }//GEN-LAST:event__20MouseClicked

    private void _21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__21MouseClicked
         if(arr[2][1]==0){
        if((coins1==0)&&(th==false))
          msg.setText("coins over//");
      if((coins2==0)&&(th==true))
          msg.setText("coins over//");
      else{
          
           if(th){
               coins2--;
           _21.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/2.png")); 
           arr[2][1]=2;
           chk(2);
         }
        else
        {   coins1--;
           _21.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/1.png")); 
           arr[2][1]=1; 
           chk(1);
        }
         
      }
       if(th)
           th=false;
       else
           th=true;}    }//GEN-LAST:event__21MouseClicked

    private void _22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__22MouseClicked
         if(arr[2][2]==0){
        if((coins1==0)&&(th==false))
          msg.setText("coins over//");
      if((coins2==0)&&(th==true))
          msg.setText("coins over//");
      else{
          
           if(th){
               coins2--;
           _22.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/2.png")); 
           arr[2][2]=2;
           chk(2);
         }
        else
        {   coins1--;
           _22.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/1.png")); 
           arr[2][2]=1; 
           chk(1);
        }
         
      }
       if(th)
           th=false;
       else
           th=true;}
    }//GEN-LAST:event__22MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             for(int i=0;i<=2;i++){
            for(int j=0;j<=2;j++){
                arr[i][j]=0;
            }
        }
             _00.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png"));
             _01.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png"));
             _02.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png"));
             _10.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png"));
             _11.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png"));
             _12.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png"));
             _20.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png"));
             _21.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png"));
             _22.setIcon(new javax.swing.ImageIcon("/home/killer/Desktop/non.png"));
             coins1=5;
             coins2=5;
             th=false;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      gamesone go=new gamesone(a);
      go.setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    public void chk(int l){
        if((arr[0][0]==arr[0][1])&&(arr[0][1]==arr[0][2]))
        {
            if(arr[0][0]==1){
                Won w=new Won(a);
                
                w.setVisible(true);
                dispose();
                }
            else if(arr[0][0]==2)
                {
                Won w=new Won(b);
                w.setVisible(true);
                dispose();
                }
        }
         if((arr[0][0]==arr[1][0])&&(arr[2][0]==arr[1][0]))
        {
            if(arr[0][0]==1)
                {
                Won w=new Won(a);
                w.setVisible(true);
              dispose();
                }
            else if(arr[0][0]==2)
                {
                Won w=new Won(b);
                w.setVisible(true);
               dispose();
                }
        }
          if((arr[0][1]==arr[1][1])&&(arr[1][1]==arr[2][1]))
        {
            if(arr[0][1]==1)
              {
                Won w=new Won(a);
                w.setVisible(true);
               dispose();
                }
            else if(arr[0][1]==2)
              {
                Won w=new Won(b);
                w.setVisible(true);
               dispose();
                }
        }
           if((arr[0][2]==arr[1][2])&&(arr[1][2]==arr[2][2]))
        {
            if(arr[0][2]==1)
                {
                Won w=new Won(a);
                w.setVisible(true);
                dispose();
                }
            else if(arr[0][2]==2)
               {
                Won w=new Won(b);
                w.setVisible(true);
               dispose();
                }
        }
         if((arr[1][0]==arr[1][1])&&(arr[1][1]==arr[1][2]))
        {
            if(arr[1][0]==1)
                {
                Won w=new Won(a);
                w.setVisible(true);
                dispose();
                }
            else if(arr[1][0]==2)
                {
                Won w=new Won(b);
                w.setVisible(true);
               dispose();
                }
        }
           if((arr[2][0]==arr[2][1])&&(arr[2][1]==arr[2][2]))
        {
            if(arr[2][0]==1)
                  {
                Won w=new Won(a);
                w.setVisible(true);
                dispose();
                }
            else if(arr[2][0]==2)
                  {
                Won w=new Won(b);
                w.setVisible(true);
              dispose();
                }
        }
              if((arr[0][0]==arr[1][1])&&(arr[1][1]==arr[2][2]))
        {
            if(arr[0][0]==1)
                  {
                Won w=new Won(a);
                w.setVisible(true);
               dispose();
                }
            else if(arr[0][0]==2)
                  {
                Won w=new Won(b);
                w.setVisible(true);
                dispose();
                }
        }
            if((arr[0][2]==arr[1][1])&&(arr[2][0]==arr[1][1]))
        {
            if(arr[0][2]==1)
                  {
                Won w=new Won(a);
                w.setVisible(true);
               dispose();
                }
            else if(arr[0][2]==2)
                 {
                Won w=new Won(b);
                w.setVisible(true);
               dispose();
                }
        }
           
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tic2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tic2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tic2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tic2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tic2("Player1","player2").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _00;
    private javax.swing.JLabel _01;
    private javax.swing.JLabel _02;
    private javax.swing.JLabel _10;
    private javax.swing.JLabel _11;
    private javax.swing.JLabel _12;
    private javax.swing.JLabel _20;
    private javax.swing.JLabel _21;
    private javax.swing.JLabel _22;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel msg;
    // End of variables declaration//GEN-END:variables
}
